/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import Class.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HENRYTO
 */
public class JFramMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFramMenu
     */
     private ListaPedidos listaPedidos;
    public JFramMenu() {
        initComponents();
        String[] columnas = {"ID", "Nombre Producto", "Cantidad", "Dirección Envío", "Nombre Cliente"};

// modelo de la tabla con los nombres de las columnas
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

// Asignacion modelo a la tabla
        jTable1.setModel(modelo);

        this.listaPedidos = new ListaPedidos();// Creamos una lista de pedidos vacía al iniciar el JFrame
        cargarPedidos();// Cargamos los pedidos en la tabla al iniciar
    }
   
  private void cargarPedidos() {
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpiamos la tabla

        Nodo actual = listaPedidos.getPrimerNodo();
        while (actual != null) {
            Pedido pedido = actual.getPedido();
            modelo.addRow(new Object[]{
                pedido.getId(),
                pedido.getProducto().getNombre(),
                pedido.getCantidad(),
                pedido.getDireccionEnvio(),
                pedido.getCliente().getNombre()
            });
            actual = actual.getSiguiente();
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jlCiudad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 290, -1));

        jlCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/city.png"))); // NOI18N
        jlCiudad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jlCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 354, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 501, 166));

        jPanel2.setBackground(new java.awt.Color(136, 212, 234));

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setText("Lista de Pedidos");

        addButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        addButton.setText("Agregar");
        addButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editButton.setText("Editar");
        editButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        deleteButton.setText("Eliminar");
        deleteButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        refreshButton.setText("Actualizar");
        refreshButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 530, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // Recargar los pedidos desde la lista y mostrarlos en la tabla
        cargarPedidos();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Recopilar el ID del pedido a eliminar
        int idPedido = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del pedido a eliminar: "));

        // Verificar si el pedido existe antes de intentar eliminarlo
        if (!listaPedidos.existeIdPedido(idPedido)) {
            JOptionPane.showMessageDialog(null, "El pedido con ID " + idPedido + " no existe.");
        } else {
            // Eliminar el pedido de la lista
            listaPedidos.eliminarPedido(idPedido);

            // Recargar la tabla para reflejar los cambios
            cargarPedidos();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // Solicitar al usuario que ingrese el ID del pedido que desea editar
        int idPedidoEditar = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del pedido que desea editar: "));

        // Verificar si el pedido con ese ID existe en la lista
        Nodo actual = listaPedidos.getPrimerNodo();
        boolean pedidoEncontrado = false;
        while (actual != null) {
            if (actual.getPedido().getId() == idPedidoEditar) {
                pedidoEncontrado = true;
                break;
            }
            actual = actual.getSiguiente();
        }

        if (!pedidoEncontrado) {
            JOptionPane.showMessageDialog(null, "El pedido con el ID especificado no existe.");
            return;
        }

        // Solicitar al usuario la nueva cantidad y la nueva dirección de envío
        int nuevaCantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la nueva cantidad: "));
        String nuevaDireccionEnvio = JOptionPane.showInputDialog("Ingrese la nueva dirección de envío: ");

        // Llamar al método editarPedido() para actualizar el pedido
        listaPedidos.editarPedido(idPedidoEditar, nuevaCantidad, nuevaDireccionEnvio);

        // Recargar la tabla para mostrar los cambios
        cargarPedidos();
    }//GEN-LAST:event_editButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // Lógica para el botón "Agregar"
        // Recopilar información del nuevo pedido
        int idPedido = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del pedido: "));
        String nombreProducto = JOptionPane.showInputDialog("Ingrese el nombre del producto: ");
        String descripcionProducto = JOptionPane.showInputDialog("Ingrese la descripción del producto: ");
        double precioProducto = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el precio del producto: "));
        int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad: "));
        String direccionEnvio = JOptionPane.showInputDialog("Ingrese la dirección de envío: ");
        String nombreCliente = JOptionPane.showInputDialog("Ingrese el nombre del cliente: ");
        String direccionCliente = JOptionPane.showInputDialog("Ingrese la dirección del cliente: ");

        // Verificar si el pedido ya existe
        if (listaPedidos.existeIdPedido(idPedido)) {
            JOptionPane.showMessageDialog(null, "El pedido con ID " + idPedido + " ya existe.");
        } else {
            // Crear un nuevo objeto Pedido con la información recopilada
            Producto producto = new Producto(nombreProducto, descripcionProducto, precioProducto);
            Cliente cliente = new Cliente(nombreCliente, direccionCliente);
            Pedido nuevoPedido = new Pedido(idPedido, producto, cantidad, direccionEnvio, cliente);

            // Agregar el nuevo pedido a la lista de pedidos
            listaPedidos.agregarPedido(nuevoPedido);

            // Recargar la tabla para mostrar el nuevo pedido
            cargarPedidos();
        }

        // Recargar la tabla para mostrar el nuevo pedido
        cargarPedidos();
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlCiudad;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel logo;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
